[project]
name = "mystack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pinecone[asyncio,grpc]==6.*",
]

[dependency-groups]
dev = [
    "jupyterlab>=4.5.2",
]
